### PR TITLE
[issue #8] creating dirs on outfile path if missing

### PR DESCRIPTION
**Pull request by hoefling**
Suggestion for issue #8

### CODE REVIEW

**Comment by hoefling** [comment]
You're right, my bad! I'm not sure about it, but would prefer not to swallow the `OSError` here - it may also indicate a full partition or insufficient file permissions. What do you say?

**Comment by johnnoone** [comment]
Your PR looks good to me.
About the `OSError` issue, let's postpone the resolution to the day someone face this problem.

Tell me if you're OK with it, and I'll merge and push the version to Pypi.

**Comment by hoefling** [comment]
I'm totally OK with it :-)

**Comment by johnnoone** [comment]
it's release on pypi : https://pypi.python.org/pypi/setuptools-lint

thanks for your contribution!

**Comment by hoefling** [comment]
Yay, updating deps for my jenkins jobs right now! Thank you for an open-minded and quick response!

**Pull request merged**
